// Code generated by mockery v2.43.2. DO NOT EDIT.

package appetizer

import mock "github.com/stretchr/testify/mock"

// MockDependencies is an autogenerated mock type for the Dependencies type
type MockDependencies struct {
	mock.Mock
}

type MockDependencies_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDependencies) EXPECT() *MockDependencies_Expecter {
	return &MockDependencies_Expecter{mock: &_m.Mock}
}

// NewMockDependencies creates a new instance of MockDependencies. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDependencies(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDependencies {
	mock := &MockDependencies{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
